deaths_word_cloud = [{text: 'Brazil', size: 130},
{text: 'Indonesia', size: 88},
{text: 'Peru', size: 39},
{text: 'Madagascar', size: 36},
{text: 'Papua New Guinea', size: 34},
{text: 'Bolivia', size: 33},
{text: 'Tanzania', size: 31},
{text: 'Chile', size: 30},
{text: 'East Timor', size: 30},
{text: 'Argentina', size: 30},
{text: 'Zambia', size: 30},
{text: 'South Africa', size: 30},
{text: 'New Zealand', size: 30},
{text: 'Fiji', size: 30},
{text: 'Kenya', size: 30},
{text: 'Vanuatu', size: 30},
{text: 'Ecuador', size: 30},
{text: 'Democratic Republic of the Congo', size: 30},
{text: 'Australia', size: 30},
{text: 'Swaziland', size: 30},
{text: 'Namibia', size: 20},
{text: 'Mauritius', size: 20},
{text: 'American Samoa', size: 20},
{text: 'Malawi', size: 20},
{text: 'Solomon Islands', size: 20},
{text: 'Angola', size: 20}
];
